import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Callout from "#components/molecules/callout";
import Button from "#components/atoms/button";
import Footer from "#components/organism/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="h-fit bg-dark min-h-screen min-w-screen max-w-full text-muted relative overflow-hidden">
          {children}
          <section className="h-fit px-52 py-5 flex flex-col gap-20">
              <Callout message="We've prepared everything, it's time for you to tell the problem">
                <Button>Send Quote</Button>
                <Button colorVariant="light">Ask Us</Button>
              </Callout>
                  <Footer
                      list={
                          [
                              {
                                  title: "Services",
                                  items: [
                                      {
                                          name: "Web Development",
                                          href: "#"
                                      },
                                      {
                                          name: "App Development",
                                          href: "#"
                                      },
                                      {
                                          name: "UI Design",
                                          href: "#"
                                      },
                                      {
                                          name: "Consultation",
                                          href: "#"
                                      },
                                      {
                                          name: "Maintenance",
                                          href: "#"
                                      },
                                  ]
                              },
                              {
                                  title: "Company",
                                  items: [
                                      {
                                          name: "About",
                                          href: "#"
                                      },
                                      {
                                          name: "Contact",
                                          href: "#"
                                      },
                                      {
                                          name: "Send Quote",
                                          href: "/quote"
                                      },
                                      {
                                          name: "Privacy Policy",
                                          href: "#"
                                      },
                                      {
                                          name: "Term of Service",
                                          href: "#"
                                      },
                                      {
                                          name: "Jobs",
                                          href: "#"
                                      },
                                  ]
                              },
                              {
                                  title: "Resources",
                                  items: [
                                      {
                                          name: "Support",
                                          href: "#"
                                      },
                                      {
                                          name: "Documentation",
                                          href: "#"
                                      },
                                      {
                                          name: "License",
                                          href: "#"
                                      },
                                      {
                                          name: "Sitemap",
                                          href: "#"
                                      },
                                  ]
                              },
                          ]
                      } />
          </section>
        </main>
      </body>
    </html>
  );
}
